development:
  adapter: postgresql
  encoding: unicode
  database: chicago-cube_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: chicago-cube_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: chicago-cube_production
  pool: 5
  username: 
  password: